#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=05:00:00
#PBS -j oe
#PBS -N SpotCheck

 cd $PBS_O_WORKDIR

#time /gpfs/home/cws161/xc_integral_unit-test/x_test_int.exe > out
 time ../x_test_int.exe > out

#XXX -q lionxn-soh3
