#!/bin/bash

#PBS -l nodes=1:ppn=12
#PBS -l walltime=04:00:00
#PBS -l mem=94gb
#PBS -q lionxf-soh3
#PBS -j oe
#PBS -N LiPs

 cd $PBS_O_WORKDIR

 export OMP_NUM_THREADS=12
 export OMP_STACKSIZE=200MB
 export OMP_SCHEDULE='guided,1'
#export OMP_SCHEDULE='static,1'

 EXEDIR=/gpfs/home/cws161/XCHF1_INDEPENDENT1-a
 EXE=runXCOMPMD6

time $EXEDIR/$EXE.exe > xcOMPout.log

#cp FinalCE.dat $WORKDIR/guessCE.inp
#cp FinalCP.dat $WORKDIR/guessCP.inp

#cp xcOMPout.log $WORKDIR

 rm GAM_* eov* nov* ENUCR* WORK15*
