#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l walltime=48:00:00
#PBS -q lionxn-soh3
#PBS -j oe
#PBS -N TEST_02

 export OMP_NUM_THREADS=32

 MAIN=/gpfs/home/cws161/XCHF1_INDEPENDENT

 EXE=runXCOMP_MD.exe

 cd $PBS_O_WORKDIR

 time $MAIN/$EXE > xcOMP_MD_out.log

