#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l walltime=96:00:00
#PBS -q lionxn-soh3
#PBS -j oe
#PBS -N TEST_AEAC

 export OMP_NUM_THREADS=8

 MAIN=/gpfs/home/cws161/XCHF1_INDEPENDENT

 EXE=runXCOMP_AEAC.exe

 cd $PBS_O_WORKDIR

 time $MAIN/$EXE > xcOMP_AEAC_out.log

