#!/bin/bash

#PBS -l nodes=1:ppn=2
#PBS -l walltime=01:00:00
#PBS -l mem=2gb
#PBS -q lionxf-soh3
#PBS -j oe
#PBS -N EXAM02

 cd $PBS_O_WORKDIR

 echo $PBS_JOBID >> JOB_STATS.txt
 echo $TMPDIR >> JOB_STATS.txt
 cat $PBS_NODEFILE >> JOB_STATS.txt

 cp guessCE.inp $TMPDIR
#cp guessCP.inp $TMPDIR
 cp basis_definition.inp $TMPDIR

 cd $TMPDIR

 export OMP_NUM_THREADS=2
 export OMP_STACKSIZE=200MB
 export OMP_SCHEDULE=GUIDED

 EXEDIR=/gpfs/home/cws161/NEO-XCHF-v1.1

 EXE=runNEOXCHF 

 $EXEDIR/$EXE.exe > xcOMPout.log

 rm GAM_* ENUCR* eovlap* novlap* WORK15

 cp xcOMPout.log $PBS_O_WORKDIR
 cp FinalCE.dat $PBS_O_WORKDIR
 cp FinalCP.dat $PBS_O_WORKDIR

