#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l walltime=96:00:00
#PBS -q lionxn-soh3
#PBS -j oe
#PBS -N TEST_AE

 export OMP_NUM_THREADS=32

 MAIN=/gpfs/home/cws161/XCHF1_INDEPENDENT

 EXE=runXCOMPAE

 cd $PBS_O_WORKDIR

 time $MAIN/$EXE.exe > xcOMPAEout.log

