#!/bin/bash

#PBS -l nodes=1:ppn=12
#PBS -l walltime=48:00:00
#PBS -l mem=94gb
#PBS -q lionxf-soh3
#PBS -j oe
#PBS -N XCUHF_TEST_02

 cd $PBS_O_WORKDIR

 echo $PBS_JOBID >> JOB_STATS.txt
 echo $TMPDIR >> JOB_STATS.txt
 cat $PBS_NODEFILE >> JOB_STATS.txt

#cp guessC*.inp $TMPDIR
#cp guessCP.inp $TMPDIR
#cp basis_definition.inp $TMPDIR

#cd $TMPDIR

 export OMP_NUM_THREADS=12
 export OMP_STACKSIZE=200MB
 export OMP_SCHEDULE=GUIDED

 /gpfs/home/cws161/XCHF1_GEffD/DENSUHF.exe > dens.out


