#!/bin/bash

FIL=$@

F77=ifort
#OPT='-openmp -parallel -fpp -traceback -check all -integer-size 64 -c'
OPT='-O2 -openmp -parallel -fpp -traceback -integer-size 64 -fp-model strict -no-ftz -ipo -c'    # ifort_O2_opts
#OPT='-O2 -openmp -integer-size 64 -c'    # ifort_O2

#F77=openf90
#OPT='-O2 -mp -i8 -no-ftz -ipa -c'    # open64_O2_opts

set echo

echo Compiling $FIL with $F77 with options $OPT ...

$F77 $OPT $FIL

echo Done.

unset echo

