#!/bin/bash

FIL=$@

F77=ifort
#OPT='-openmp -parallel -fpp -traceback -check all -integer-size 64 -c'                            # Chet's options
OPT='-O2 -openmp -integer-size 64 -fp-model strict -no-ftz -ipo -c'                                # UIUC cluster options
#OPT='-O2 -openmp -openmp-link static -integer-size 64 -fp-model strict -no-ftz -xHOST -ipo -c'    # LionXF/PSU cluster options
#OPT='-O2 -openmp -traceback -check all -integer-size 64 -fp-model strict -no-ftz -ipo -c'         # Debug options

set echo

echo Compiling $FIL with $F77 with options $OPT ...

$F77 $OPT $FIL

echo Done.

unset echo

