#!/bin/bash

echo "Cleaning ../object/ before compiling..."
rm ../object/*.o

FILS='xcneo_HYBRID.f gam_ee.f gam_1_OMP.f gam_2_OMP.f gam2_CONV_OMP.f gam2_DSCF_OMP.f gam2_IC1_OMP.f gam_3_OMP.f gam3_DSCF_OMP.f gam3_CONV_OMP.f gam3_IC1_OMP.f gam3_IC2_OMP.f gam_4_OMP.f gam4_DSCF_OMP.f gam4_ICR_OMP.f'

./comp $FILS
mv *.o ../object

cd xchf1_independent/
../comp *.f
mv *.o ../../object

cd ../CS_Integrals/
../comp *.f
mv *.o ../../object

cd Spot_Check/
../../comp pack_GAM.f zero_gam.f
mv *.o ../../../object

cd ../../AC_Integrals/
../comp *.f
mv *.o ../../object

cd ../xcuhf/
../comp *.f
mv *.o ../../object

cd ../rxchf/
../comp *.f
mv *.o ../../object

cd ../rxchfne/
../comp *.f
mv *.o ../../object

cd ../rxchfmult/
../comp *.f
mv *.o ../../object

