#!/bin/bash

if [ $# -lt 1 ] ; then
 echo "Usage: $0 [executable]"
 echo "Generated executable will be [executable].exe in ../bin"
 exit 0
fi

EXEDIR=../bin
EXE=$1

if [ -e $EXEDIR/$EXE.exe ] ; then
  echo "Executable $EXE.exe exists in ../bin. Exiting..."
  exit 0
fi

# OpenMP compilation
#F77=ftn
#OPT='-openmp -parallel -fpp -traceback -check all -integer-size 64'                            # Chet's options
#OPT='-O2 -openmp -integer-size 64 -fp-model strict -no-ftz'                                # UIUC cluster options
#OPT='-O2 -openmp -openmp-link static -integer-size 64 -fp-model strict -no-ftz -xHOST -ipo'    # LionXF/PSU cluster options
#OPT='-O2 -openmp -traceback -check all -integer-size 64 -fp-model strict -no-ftz -ipo'         # Debug options
#OPT='-O2 -fast -mp=nonuma -i8 -r8 -Mnoflushz -Ktrap=fp'
#
# Hybrid MPI/OpenMP compilation
F77=ftn
#OPT='-O2 -openmp -integer-size 64 -fp-model strict -no-ftz -ipo' # Intel
#OPT='-O2 -mp=nonuma -i8 -i8storage -r8 -Mnoflushz -Ktrap=fp' # PGI
OPT='-O2 -s default64 -Ktrap=fp -R b' #Cray

FILS='../object/*.o'

set echo

echo Using compiler $F77 with options $OPT to link files
echo
echo $FILS
echo
echo to executable $EXE.exe in ../bin

$F77 $OPT $FILS -o $EXEDIR/$EXE.exe
#ftn -O2 -s default64 -Ktrap=fp $FILS  -o $EXEDIR/$EXE.exe -L/opt/acml/5.3.0/open64_64_int64/lib -lm -lacml

echo Done.

unset echo

