#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l walltime=01:00:00
#PBS -q lionxn-soh3
#PBS -j oe
#PBS -N Z3BG

 export OMP_NUM_THREADS=8
 export OMP_STACKSIZE=2G

 MAIN=/gpfs/work/cws161/HeH+_OMP_Calcs/Z_3BG

#module load openmpi/intel/1.4.2

 cd $PBS_O_WORKDIR

 time $MAIN/runXCOMP.exe > xcOMPout.log

